### ISSUE TITLE
torch.eig is deprecated for a long time and is being removed

### ISSUE THREAD

**Issue by kit1980** [facebookresearch/neural-scs#4]
PyTorch's torch.eig was deprecated since version 1.9 and is being removed by https://github.com/pytorch/pytorch/pull/70982. Please use the torch.linalg.eig function instead if you want your code to continue to work with the latest PyTorch.

Affected file:
https://github.com/facebookresearch/neural-scs/blob/29743a161b99fcc40ce5d814aecc9f55272f1cef/automl21/enr.py#L242

**Comment by lezcano** [comment]
Interestingly enough, you can save the `ATA` multiplication there, and simply write that as 
```python
L = torch.svdvals(A).max() ** 2 + mu/2
```
. For the why, see https://en.wikipedia.org/wiki/Singular_value_decomposition#Relation_to_eigenvalue_decomposition
This is a much more stable and efficient way to compute this quantity.
